[package]
name = "oxideterm-settings"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
oxideterm-atomic-file = { path = "../oxideterm-atomic-file" }
oxideterm-portable-runtime = { path = "../oxideterm-portable-runtime" }
oxideterm-render-policy = { path = "../oxideterm-render-policy" }
oxideterm-terminal-semantic = { path = "../oxideterm-terminal-semantic", default-features = false }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.23"
