[package]
name = "oxideterm-secret-store"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
keyring.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
uuid.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
base64.workspace = true
block2 = "0.6"
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSError", "NSString"] }
