[package]
name = "oxideterm-sftp"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
flate2 = "1.1.9"
futures-util.workspace = true
glob = "0.3"
mime_guess = "2"
oxideterm-atomic-file = { path = "../oxideterm-atomic-file" }
oxideterm-preview = { path = "../oxideterm-preview" }
parking_lot.workspace = true
redb = "2.1"
rmp-serde.workspace = true
russh = { path = "../russh" }
russh-sftp = { path = "../russh-sftp" }
serde.workspace = true
sha2.workspace = true
tar = "0.4"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
zeroize.workspace = true
zstd = "0.13"

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.23"
