[package]
name = "oxideterm-terminal-graphics"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
icy_sixel.workspace = true
image.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "graphics_ingress"
harness = false
