[package]
name = "oxideterm-terminal-semantic"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []
shell-syntax = ["dep:oxideterm-editor-syntax"]

[dependencies]
oxideterm-editor-syntax = { path = "../oxideterm-editor-syntax", optional = true }
regex.workspace = true
roxmltree = "0.20"
serde.workspace = true
serde_json.workspace = true
